name: delete blob storage container
description: Deletes the given blob from the given container within the given storage account.
inputs:
  account-name:
    description: Name of the storage account of the container to delete the blob from.
    required: true
  account-key:
    description: Access key for the storage account
    required: true
  container-name:
    description: Name of the container to delete the blob from.
    required: true
  pattern:
    description: Pattern to search for and delete within the container.
    required: true

runs:
  using: composite
  steps:
    - name: Azure CLI Action
      uses: azure/cli@v2
      with:
        inlineScript: |
          az storage blob delete-batch --account-key = ${{ inputs.account-key }} --account-name ${{ inputs.account-name }} --source $ {{ inputs.container-name }} --pattern $ {{ inputs.pattern }}
