name: delete blob storage container
description: Deletes the given blob from the given container within the given storage account.
inputs:
  azure-credentials:
    description: Credentials that are used to perform the azure login.
    required: true
  account-name:
    description: Name of the storage account of the container to delete the blob from.
    required: true
  account-key:
    description: Access key for the storage account
    required: true
  container-name:
    description: Name of the container to delete the blob from.
    required: true
  blob-name:
    description: Name of the blob. If the name is a prefix all blobs with the given prefix are deletet.
    required: true

runs:
  using: composite
  steps:
    - name: magic
      shell: pwsh
      run: |
        Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        $storageAccountContext = New-AzureStorageContext -StorageAccountName '${{ inputs.account-name }}' -StorageAccountKey '${{ inputs.account-key }}'
        $blobs = Get-AzureStorageBlob -Context $storageAccountContext -Container '${{ inputs.container-name }}' -Blob '${{ inputs.blob-name }}'
        foreach($blob in $blobs) {
          Write-Output "Removing blob '$($blob.Name)'' from container '${{ inputs.container-name }}'"
        }
#          Remove-AzureStorageBlob -Context $storageAccountContext -Container '${{ inputs.container-name }}' -Blob '${{ inputs.blob-name }}'
